### PR TITLE
Merge pull request #1 from 2Tie/menu_fix

### PR DESCRIPTION
**Pull request by trovsky**
Fixed menu so the third option is disabled until you load a ROM

### CODE REVIEW

**Comment by trovsky** [comment]
The amount of lines that I changed according to Github is misleading.

**Comment by 2Tie** [comment]
what happens when you're at map 12 and click up? does it skip over 13 to 14 or stay at 12?

**Comment by 2Tie** [comment]
also, does it let you view tileset 13?

**Comment by trovsky** [comment]
It allows you to enter 13, but it does not load the map. The tileset isn't loaded either. I'm going to close this and redo it so it's easier to merge.

**Pull request closed without merging**
